// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type ClossSession struct {
	Token    string
	Username string
	UserID   string
}

type ClossUser struct {
	ID       string
	Username string
}
