// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type ClossSession struct {
	RefreshToken string
	AccessToken  string
	Username     string
	UserID       string
}
