// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package database

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
;

INSERT  INTO closs_session(
    token,
    username,
    user_id
)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token    string
	Username string
	UserID   string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.Username, arg.UserID)
	return err
}

const deleteSessionById = `-- name: DeleteSessionById :exec
;

delete from closs_session
where user_id = ?
`

func (q *Queries) DeleteSessionById(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionById, userID)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
;

delete from closs_session
where token = ?
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const getSessionById = `-- name: GetSessionById :one
select token, username, user_id
from closs_session
where user_id = ?
`

func (q *Queries) GetSessionById(ctx context.Context, userID string) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, userID)
	var i ClossSession
	err := row.Scan(&i.Token, &i.Username, &i.UserID)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
;

select token, username, user_id
from closs_session
where token = ?
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i ClossSession
	err := row.Scan(&i.Token, &i.Username, &i.UserID)
	return i, err
}

const getSessionByUsername = `-- name: GetSessionByUsername :one
;

select token, username, user_id
from closs_session
where username = ?
`

func (q *Queries) GetSessionByUsername(ctx context.Context, username string) (ClossSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUsername, username)
	var i ClossSession
	err := row.Scan(&i.Token, &i.Username, &i.UserID)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
;

UPDATE closs_session SET
    token = ?
WHERE user_id = ?
`

type UpdateSessionParams struct {
	Token  string
	UserID string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession, arg.Token, arg.UserID)
	return err
}
